apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: api-pagamentos-signed-images
spec:
  images:
    - glob: "ghcr.io/daniellarf/api-pagamentos@sha256:*"
  authorities:
    - keyless:
        identities:
          - issuer: "https://token.actions.githubusercontent.com"
            subjectRegExp: "https://github.com/daniellarf/api-pagamentos/.github/workflows/release.yml@refs/tags/v.*"
        url: "https://fulcio.sigstore.dev"
      ctlog:
        url: "https://rekor.sigstore.dev"
