name: CI Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy-and-sbom:
    name: Policy as Code e SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conftest
        run: |
          curl -sSL \
            https://github.com/open-policy-agent/conftest/releases/download/v0.69.0/conftest_0.69.0_Linux_x86_64.tar.gz \
            -o conftest.tar.gz

          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/conftest

          conftest --version

      - name: Run Rego Unit Tests
        run: |
          conftest verify --policy policies

      - name: Validate Main Dockerfile
        run: |
          conftest test Dockerfile \
            --policy policies/docker \
            --namespace docker

      - name: Validate Good Dockerfile
        run: |
          conftest test Dockerfile.good \
            --policy policies/docker \
            --namespace docker

      - name: Confirm Bad Dockerfile Is Blocked
        shell: bash
        run: |
          set +e

          conftest test Dockerfile.bad \
            --policy policies/docker \
            --namespace docker

          result=$?

          if [ "$result" -eq 0 ]; then
            echo "ERRO: Dockerfile.bad deveria ter sido reprovado."
            exit 1
          fi

          echo "Dockerfile.bad foi bloqueado corretamente."

      - name: Validate Kubernetes Manifest
        run: |
          conftest test k8s/deployment.yaml \
            --policy policies/kubernetes \
            --namespace kubernetes

      - name: Install Syft
        run: |
          curl -sSL \
            https://github.com/anchore/syft/releases/download/v1.0.0/syft_1.0.0_linux_amd64.tar.gz \
            -o syft.tar.gz

          tar -xzf syft.tar.gz
          sudo mv syft /usr/local/bin/syft

          syft version

      - name: Generate CycloneDX and SPDX SBOMs
        run: |
          mkdir -p sbom

          syft dir:. \
            -o cyclonedx-json=sbom/sbom-cyclonedx.json

          syft dir:. \
            -o spdx-json=sbom/sbom-spdx.json

      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            sbom/sbom-cyclonedx.json
            sbom/sbom-spdx.json
          if-no-files-found: error